export enum Station {
    BatuCaves = "Batu Caves",
    TamanWahyu = "Taman Wahyu",
    KampungBatu = "Kampung Batu",
    BatuKentonmen = "Batu Kentonmen",
    Sentul = "Sentul",
    Putra = "Putra",
    BankNegara = "Bank Negara",
    KualaLumpur = "Kuala Lumpur",
    KLSentral = "KL Sentral",
    Midvalley = "Midvalley",
    Seputeh = "Seputeh",
    SalakSelatan = "Salak Selatan",
    BandarTasekSelatan = "Bandar Tasek Selatan",
    Serdang = "Serdang",
    Kajang = "Kajang",
    Kajang2 = "Kajang 2",
    UKM = "UKM",
    Bangi = "Bangi",
    BatangBenar = "Batang Benar",
    Nilai = "Nilai",
    Labu = "Labu",
    Tiroi = "Tiroi",
    Seremban = "Seremban",
    Senawang = "Senawang",
    SungaiGadut = "Sungai Gadut",
    Rembau = "Rembau",
    PulauSebang = "Pulau Sebang",
  }
  